"""empty message

Revision ID: 786d4742bdbf
Revises: add356963bdb
Create Date: 2024-06-24 13:22:03.434815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786d4742bdbf'
down_revision = 'add356963bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_room_numder')
        batch_op.create_index(batch_op.f('ix_room_number'), ['number'], unique=False)
        batch_op.drop_column('numder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numder', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_room_number'))
        batch_op.create_index('ix_room_numder', ['numder'], unique=False)
        batch_op.drop_column('number')

    # ### end Alembic commands ###
