"""empty message

Revision ID: add356963bdb
Revises: fb4c38f1b9a7
Create Date: 2024-06-24 12:49:57.388753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add356963bdb'
down_revision = 'fb4c38f1b9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=False))
        batch_op.create_index(batch_op.f('ix_office_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_title'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
