"""empty message

Revision ID: fb4c38f1b9a7
Revises: 
Create Date: 2024-06-24 01:15:38.329782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4c38f1b9a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_address'), ['address'], unique=True)

    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numder', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_numder'), ['numder'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_office_id'), ['office_id'], unique=False)

    op.create_table('seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numder', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_numder'), ['numder'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_room_id'), ['room_id'], unique=False)

    op.create_table('employee_seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupation_date', sa.DateTime(), nullable=False),
    sa.Column('occupation_time', sa.DateTime(), nullable=False),
    sa.Column('occupation_duration', sa.DateTime(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('emplayee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emplayee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_seat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_seat_emplayee_id'), ['emplayee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_seat_occupation_date'), ['occupation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_seat_occupation_duration'), ['occupation_duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_seat_occupation_time'), ['occupation_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_seat_seat_id'), ['seat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_seat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_seat_seat_id'))
        batch_op.drop_index(batch_op.f('ix_employee_seat_occupation_time'))
        batch_op.drop_index(batch_op.f('ix_employee_seat_occupation_duration'))
        batch_op.drop_index(batch_op.f('ix_employee_seat_occupation_date'))
        batch_op.drop_index(batch_op.f('ix_employee_seat_emplayee_id'))

    op.drop_table('employee_seat')
    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_room_id'))
        batch_op.drop_index(batch_op.f('ix_seat_numder'))

    op.drop_table('seat')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_office_id'))
        batch_op.drop_index(batch_op.f('ix_room_numder'))

    op.drop_table('room')
    with op.batch_alter_table('office', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_address'))

    op.drop_table('office')
    op.drop_table('employee')
    # ### end Alembic commands ###
